### ISSUE TITLE
I can't figure out the yep_dirs file...

### ISSUE THREAD

**Issue by Xamusel** [nekoyoubi/yep_util#2]
So, I'm trying to modify the text file involved in the utility released so far... and so far, I can't figure out what to write for the directories. Care to remind me what I need to do?

**Comment by nekoyoubi** [comment]
Depending on what directory you run the YEP Auto-Update from, and how ever many projects you're updating will determine what your `yep_dirs.txt` will look like. If you're running it from a project's root (and for only one project total), you really just want to blank out the file. This will make it assume you're updating to the js/plugins folder of the current working directory. I, before breaking this into another folder for this repo, used to run it from a folder parallel to my RMMV projects, so my `yep_dirs.txt` looked something like:

> yep
> ..\Project1
> ..\Project2
> ..\Project3

This would create a subdirectory under my `cwd` (current working directory) named `yep\js\plugins` for posterity (so I could quickly copy & paste to a new project if needed. It would also update all of the individual projects' `js\plugins` folders to be the current version of YEP (overwriting older copies, but not removing anything in case there are other plugins).

Does that help?

**Comment by Xamusel** [comment]
Oh, yes, it helps a lot. Thank you very much.

**Comment by nekoyoubi** [comment]
Oh, and the `..\` just means "step up one directory" in pathing, if that was the confusing part.

**Comment by Xamusel** [comment]
Yeah, that did confuse me a lot, actually... I'm still not good with command prompt terms like that.

**Comment by nekoyoubi** [comment]
I may be able to write something to allow you to navigate and select projects in a visual dialog in the future, but I honestly didn't expect to put nearly this level of detail into it from the start as it started as just a tool for me to keep my projects up-to-date. I'll think on that for a bit and see if that would help make it make more sense for people.

**Comment by Xamusel** [comment]
I think it would, actually... otherwise, I'll have to do so much learning of command prompt terms.

**Comment by nekoyoubi** [comment]
I've added a new feature for adding projects to the yep_dirs.txt as requested. Also, if you run the new binaries from a project folder, no prompts will be given, and a blank yep_dirs.txt will be created. If the script/binaries are ran from a folder that does not appear to be an RMMV project, the blank file wil still be created, but an add project dialog will be presented. Thanks for the suggestion, friend.

**Comment by Xamusel** [comment]
You are most welcome.
