### ISSUE TITLE
Regarding unrar...

### ISSUE THREAD

**Issue by Xamusel** [nekoyoubi/yep_util#3]
What is that? I'm assuming you are referring to winRAR?

**Comment by nekoyoubi** [comment]
Yes. `unrar.exe` is the app that WinRAR users use to basically "unzip" the contents of YEP's .rar file. If you are using [7-Zip](http://7zip.org) (which I certainly recommend as it's what I use so it's more tested), then that setting won't matter to you at all.

**Comment by Xamusel** [comment]
Okay, just wanted to confirm. I was only curious, because I don't have 7-Zip on my computer.

**Comment by nekoyoubi** [comment]
If you have WinRAR, then yes, `unrar.exe` would be the setting in the `config.ini` that you may need to change if your WinRAR install did not include the addition to the PATH system variable. If you run into issues, you may need to change this setting to the full path to `unrar.exe` (e.g. `C:\Program Files (x86)\WinRAR\unrar.exe`), or whatever the actual path is. Other than that, just make sure you set the `Set Extraction Tool > WinRAR` in the updater before trying an update. These settings should persist as well.

**Comment by Xamusel** [comment]
Alright. I see what you're saying. Thank you for your help so far.

**Comment by nekoyoubi** [comment]
No worries. Let me know if there's anything else I can help with.
