### ISSUE TITLE
yep_util downloads RAR copy of plugins but does not extract them to project folder plugin directories

### ISSUE THREAD

**Issue by Feldherren** [nekoyoubi/yep_util#5]
7zip has been fully installed (and though the installer does not add 7zip to the path, the 7zip executable location has been added to the path) prior to attempting to use the AHK script. When attempting to update the Yanfly scripts, the AHK script successfully downloads yep_[date].rar but then reports success without extracting the plugin files to the project directories.

Attempting to use the AHK script on Windows 7 64-bit, with the 64-bit version of 7zip installed to the default location in Program Files.

**Comment by Feldherren** [comment]
Actually, may just be some weirdness with path. Some copies of cmd see the updated version and some do not.

**Comment by nekoyoubi** [comment]
Since it's reporting success, this is a good thing. That at least means that they extraction is fully taking place. At this point, I'd have to ask what your yep_dir.txt looks like, and where you're running the .ahk/.exe from (an RMMV project's root, or a separate folder)?

**Comment by nekoyoubi** [comment]
Oh, if you've changed the PATH variable manually, the only thing to confirm that the change is complete is a reboot, sadly, but typically just closing all instances of cmd will update it in new instances (there are exceptions).

**Comment by Feldherren** [comment]
I took the route of just killing and restarting explorer.exe, which got command prompt to update and recognise the 7zip directory is in path. That was being finicky, but the script is still not seeming to extract anything.

yep_autoupdate.ahk is being run from a separate folder. yep_dirs.txt looks like this:

E:\Projects\RPG Maker\Resources\RPG Maker MV\Plugins\Yanfly\yep
E:\Projects\RPG Maker\RPG Maker MV\DungeonCrawl

...\Plugins\Yanfly\yep is just a folder created for a local up to date copy of the scripts without anything else of a project about it - it just contains js\plugins, which remains stubbornly empty.
DungeonCrawl is an actual project that already has the scripts up to date in it, from a regular and manually-downloaded copy earlier today.

**Comment by nekoyoubi** [comment]
Let me run some tests and see what I can see. I'm wondering if it has something to do with the spaces in the absolute path. Is there any way you can test it with either a short relative path, or a non-spaced absolute and see what you get? That would help narrow things down a bit, I think.

**Comment by nekoyoubi** [comment]
I found that the issue does appear to be the spaced path. I've been able to test briefly in 7-Zip's case. someone will have to tell me if the fix still works with WinRAR. I'll commit the script and new binaries here in a moment. Thanks for the catch!

**Comment by Feldherren** [comment]
I don't think you can expect people not to have spaces in path, considering this is the default install location for 7zip, which has spaces in it.

Feeding it the full path to 7z.exe doesn't work. Feeding it the path to 7za.exe (standalone console version) doesn't work, either, but I wasn't entirely expecting that to work. Dropping 7za.exe and dlls into the folder yep_autoupdate.ahk is running from (and telling it the path is 7za.exe) also doesn't work.
Copying the entirety of 7zip's files to another path with no spaces and pointing config.ini at that doesn't work, either.

**Comment by nekoyoubi** [comment]
No, no, no. I wasn't at all saying that there _shouldn't_ be spaces in the path; just that I thought that may be the issue, which I believe it was. Any chance you can try the new commit, and let me know if that works for you?

**Comment by Feldherren** [comment]
Didn't mean it that way. Had most of that typed before you posted that reply, and didn't notice you had replied until I'd posted.

Yes, that did indeed work.

**Comment by nekoyoubi** [comment]
Awesome! Thanks for your help catching this. I've had a few emails that I think will be resolved with this as well. Good work!
