### ISSUE TITLE
Here's another issue I think you need to know about

### ISSUE THREAD

**Issue by Xamusel** [nekoyoubi/yep_util#6]
I was doing some work last night, making sure I could get this to work for me, when I got the updates downloaded. Naturally, this would be a good thing, except that it almost immediately went into an error (which I'll type in here because I can't copy-paste it for whatever reason):

Error: Failed attempt to launch program or document
Action: <unrar.exe>
Params: <x yep_2015.12.30.rar -o+ *insert directory here*>

Specifically: The system cannot find the file specified.

Then it gives me a Line Number 172 (can't use the number sign in this for some reason) thing.

Care to explain what went wrong? Thank you.

**Comment by nekoyoubi** [comment]
And this was with the most recent build, v0.10?

**Comment by Xamusel** [comment]
I take it this was released as of 17-18 hours ago? If so, yes.

**Comment by nekoyoubi** [comment]
It was, yes, but I'm not sure what line 172 would refer to, as there is no code at 172 in the v0.10. When you're copying & pasting, if you put three ` characters on a line before, and again after, it will treat your text inside as a code block and shouldn't reformat. Also, a screenshot would work.

Are you using WinRAR, by chance? (Still untested after last night's quoted update.)

**Comment by Xamusel** [comment]
Yes, still using WinRAR, actually.

Also, I couldn't copy-paste, for some odd reason. I'll grab a screenshot for ya soon enough.

**Comment by nekoyoubi** [comment]
Awesome. It would be much appreciated. I just checked my various projects, and it looks like they updated last night naturally with no exceptions thrown, so I'm guessing it's either a configuration issue (possibly need to test quoting the archive tool path also), or a WinRAR specific issue. I may need to get WinRAR just to test some of these things, but I don't know how the trial verison would impact the CLI.

**Comment by Xamusel** [comment]
![screenshot002](https://cloud.githubusercontent.com/assets/7400526/12067185/6119ae22-afaa-11e5-9061-92f7ecdac66e.png)

Here's the screenshot... and, honestly, I'm using the trial version of WinRAR. I don't know if it'll affect things like that or not.

**Comment by nekoyoubi** [comment]
That appears to be a problem finding WinRAR. What does your WinRARPath= setting say in your config.ini? Is it the PATH-expecting "unrar.exe", or is it a fully qualified path like "C:\Program Files\WinRAR\unrar.exe"?

**Comment by Xamusel** [comment]
...I feel like an idiot. It's the former.

**Comment by Xamusel** [comment]
...it did it again!! I put in the full path of the program as well.

**Comment by nekoyoubi** [comment]
So it's still happening with the full path for the tool? In that case you're probably discovering that the changes may not work for WinRAR. Let me go install the trial and see what I can see.

On a side note, I'm guessing when you downloaded the new version, you got the `config.ini` again as well, yes? All apologies for that. I should probably move that into the `/doc` so people don't accidentally overwrite their custom configs in updates. The script builds it anyway if it doesn't exists, so it's not needed. I only allowed it to be included so people could reference it if they screwed up their configs accidentally.

**Comment by Xamusel** [comment]
I think it might have been redownloaded, the congif.ini, but I don't really know. I opened the file from my projects' root folder... I'll have to check.

**Comment by nekoyoubi** [comment]
Okay, I've finally finished stumbling all over my keyboard like a punch-drunk boxer, and pushed a new commit with what I hope will be a fix to your (and others') issues. Please let me know how this works out for you.

**Comment by Xamusel** [comment]
Will do... hang on, working on getting the commit on my computer.

**Comment by Xamusel** [comment]
...did you forget to modify the .exe file?

**Comment by nekoyoubi** [comment]
I did, but I added them by the time I mentioned it here. Is it still giving the same issue?

**Comment by nekoyoubi** [comment]
Great. Now I'm not seeing them. Sec.

**Comment by nekoyoubi** [comment]
Yep; committed... just never sync'd to github. ;(  Rough day.

**Comment by Xamusel** [comment]
It's fine. Glad you got them sync'd.

Let me take it for a spin now.

**Comment by Xamusel** [comment]
Yay!! It works now!

**Comment by nekoyoubi** [comment]
Awesome! Glad to hear it. Please let me know if I can break anything else for you. ;x  Wait... no, that's not right... ;)
