### ISSUE TITLE
I have no idea what I'm doing

### ISSUE THREAD

**Issue by SamuelKeller64** [nekoyoubi/yep_util#7]
## yep_autoupdate_64bit.exe

Error:  Failed attempt to launch program or document:
Action: <7z.exe>
Params: <x yep_2016.01.25.rar -aoa -o"C:\Users\Brandon\Desktop\My Flashdrive\CrazyIdea\Project3\yep_util-master\yep_autoupdate\bin\js\plugins">

Specifically: The system cannot find the file specified.

```
Line#
```

--->    173: RunWait,"%au7zPath%" x yep_%updated1%.rar -aoa -o"%A_LoopReadLine%\js\plugins",,hide
## OK   

For clarification, CrazyIdea and Project3 are the names of my project, with the first being the folder its contained in and the second being the actual project. Any reasons it's giving me this message?

**Comment by nekoyoubi** [comment]
Okay, so first off, I'm guessing you either don't have 7-Zip installed, or have it installed but not on the PATH variable (and if you don't know what I mean there, it's no biggie). Second, you don't need to download the entire project if you're not interested in editing the tool; just pick up the binary (.exe) for your type of system (probably 64-bit it sounds like).

I would recommend downloading it to a folder above your projects (e.g. if your projects are `C:\RMMV\ProjA`, and `C:\RMMV\ProjB`, then put the .exe in `C:\RMMV`).

When you run it you'll be prompted to choose a project location; do so. Then add your second project from the menu option.

After you have it running from there and giving the error you reported when you try to update, you're ready to get your extraction tool setup. First choose whether you'll be using 7-Zip or WinRAR (7-Zip is free and open source; WinRAR is shareware). Once you know which one you're using, set it via the tool's menu. If you chose 7-Zip, and had it installed before posting this issue, then it's not on your PATH. Open the config file via the menu, and edit the `7ZipPath=` option to the full path to your `7z.exe` (e.g. `7ZipPath=C:\Program Files\7-Zip\7z.exe`).

Please let me know if you have any further issues, and if you'd like, I can attempt to walk your through it via Discord.

**Comment by nekoyoubi** [comment]
Oh, and in case I missed something, most of what I typed there is covered here: https://github.com/nekoyoubi/yep_util/blob/master/yep_autoupdate/README.md

**Comment by SamuelKeller64** [comment]
It's working as intended, thank you for your support.

**Comment by nekoyoubi** [comment]
Never a problem. Thanks for letting me help, and also for letting me know your issues are resolved. Please let me know if you have any further questions, or need any assistance.
